version: '3.8'

services:
  symfony-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: symfony-demo-test
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/var/cache
      - /var/www/html/var/log
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - /tmp/opcache:/tmp/opcache
      - /tmp/sessions:/tmp/sessions
    environment:
      - APP_ENV=test
      - APP_SECRET=test-secret-for-ci
      - DATABASE_URL=sqlite:///var/www/html/data/database_test.sqlite
      - SYMFONY_DEPRECATIONS_HELPER=disabled
      - SYMFONY_ISOLATE_MACOS_TESTS=1
      - MEMORY_LIMIT=768M
      # SQLite optimizations for Docker on macOS
      - SQLITE_TEMP_STORE=memory
      - SQLITE_JOURNAL_MODE=wal
      - SQLITE_SYNCHRONOUS=off
    working_dir: /var/www/html
    command: /bin/sh -c "mkdir -p data && chmod 777 data && php vendor/bin/phpunit"
    networks:
      - test-network
    # Add health check to ensure container is ready
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  test-network:
    driver: bridge

volumes:
  opcache_cache:
    driver: local
  session_data:
    driver: local